# Default values for starter-kit-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "INFO"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 9080

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""
