{{- if .Values.rbac.ocpCreate -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "starter-kit.fullname" . }}-scc-role"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
    - ibm-websphere-scc
{{- end }}
