{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "starter-kit.fullname" . }}-psp-use-pod-security-policy-role"
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
    - "{{ include "starter-kit.fullname" . }}-psp-pod-running-policy"
{{- end }}
